#tmux has-session -t development
#if [ $? != 0 ]
#then
#  tmux new-session -s development
#fi
#tmux attach -t development

#delete all unattached tmux sessions
tmux list-sessions -F '#{session_attached} #{session_id}' | \
  awk '/^0/{print $2}' | \
  xargs -n 1 tmux kill-session -t

#create new tmux session
tmux

#change the prompt line
PS1="\e[0;34m\u\e[0m\e[0;34m@\e[0m\e[0;31m\w\e[0m \e[0;34m~$\e[0m "
#a variable with a line for echos
LINE="-----------------------------------"

# all my aliases
alias cdopt="cd ~/options"
alias cdesk="cd ~/Escritorio"
alias cdoc="cd ~/Documentos"
alias cdimg="cd ~/Imágenes"
alias cdownloads="cd ~/Descargas"

alias clientenglish="npm --prefix ~/Escritorio/programming/english-assistant/client/ run dev"
alias serverenglish="npm --prefix ~/Escritorio/programming/english-assistant/server/ start"
alias cdash="cd ~/Escritorio/work/dashboards"

alias c="clear"

alias bi="ssh jesus@bicyt.xyz"
alias cdash="cd ~/Escritorio/work/dashboards"

alias e="exit"
alias ..="cd .."

#print alises loaded for debuggin when it's necessary
echo "aliases loaded"
echo $LINE

#configuration for fzf module (vim)
export FZF_DEFAULT_COMMAND='rg --files --follow --no-ignore-vcs --hidden -g "!{node_modules/*,.git/*,.next/*,out/,dist/}"'

# initial commands
cd Escritorio/
free -m
echo $LINE
tmux ls
